# Installs rake tasks for gemming and packaging
#
# This file installs the 'rake package', 'rake gem' tasks and associates
# (clobber_package, repackage, ...). It is automatically generated by Noe
# from your .noespec file, and should therefore be configured there, under
# the variables/rake_tasks/gem entry, as illustrated below:
#
# variables:
#   rake_tasks:
#     gem:
#       package_dir: pkg
#       need_tar: false
#       need_tar_gz: false
#       need_tar_bz2: false
#       need_zip: false
#       ...
#
# If you have specific needs requiring manual intervention on this file,
# don't forget to set safe-override to false in your noe specification:
#
# template-info:
#   manifest:
#     tasks/gem.rake:
#       safe-override: false
#
begin
  require 'rubygems/package_task'
  Gem::PackageTask.new($gemspec) do |t|

    # Name of the package
    t.name = $gemspec.name

    # Version of the package
    t.version = $gemspec.version

    # Directory used to store the package files
    t.package_dir = +{rake_tasks.gem.package_dir}

    # True if a gzipped tar file (tgz) should be produced
    t.need_tar = +{rake_tasks.gem.need_tar}

    # True if a gzipped tar file (tar.gz) should be produced
    t.need_tar_gz = +{rake_tasks.gem.need_tar_gz}

    # True if a bzip2'd tar file (tar.bz2) should be produced
    t.need_tar_bz2 = +{rake_tasks.gem.need_tar_bz2}

    # True if a zip file should be produced (default is false)
    t.need_zip = +{rake_tasks.gem.need_zip}

    # List of files to be included in the package.
    t.package_files = $gemspec.files

    # Tar command for gzipped or bzip2ed archives.
    t.tar_command = +{rake_tasks.gem.tar_command}

    # Zip command for zipped archives.
    t.zip_command = +{rake_tasks.gem.zip_command}

  end
rescue LoadError
  task :gem do
    abort 'rubygems/package_task is not available. You should verify your rubygems installation'
  end
  task :package do
    abort 'rubygems/package_task is not available. You should verify your rubygems installation'
  end
end
