source 'http://rubygems.org'

group :default do 
  !{dependencies.collect{|dep| "gem '#{dep['name']}', '#{dep['version']}'"}.join("\n  ")}
end

group :development do 
  !{devel_dependencies.collect{|dep| "gem '#{dep['name']}', '#{dep['version']}'"}.join("\n  ")}
end
