# Dynamically load the gem spec
$gemspec_file = File.expand_path('../!{lower}.gemspec', __FILE__)
$gemspec      = Kernel.eval(File.read($gemspec_file))

# We run tests by default
task :default => :spec

#
# Install all tasks found in tasks folder
#
# See .rake files there for complete documentation.
#
Dir["tasks/*.rake"].each do |taskfile|
  instance_eval File.read(taskfile), taskfile
end
